const path = require('path');
const webpack = require('webpack');
const MFS = require('memory-fs');

module.exports = function setupDevServer(serverConfig, app, onUpdate) {
  let bundle;
  let ready;
  const readyPromise = new Promise((r) => { ready = r; });
  const update = () => {
    if (bundle) {
      ready();
      onUpdate(bundle);
    }
  };

  // watch and update server renderer
  const serverCompiler = webpack(serverConfig);
  const mfs = new MFS();
  // const outputPath = path.join(serverConfig.output.path, serverConfig.output.filename);
  const outputPath = path.join(serverConfig.output.path, 'manifest/server.json');

  serverCompiler.outputFileSystem = mfs;
  serverCompiler.watch({}, (err, stats) => {
    if (err) throw err;
    const jsonStats = stats.toJson();
    jsonStats.errors.forEach(err => console.error(err));
    jsonStats.warnings.forEach(err => console.warn(err));

    // read bundle generated by vue-ssr-webpack-plugin
    bundle = JSON.parse(mfs.readFileSync(outputPath, 'utf-8'));
    update();

    onUpdate(bundle);
  });

  return readyPromise;
};
